Making the following configurables an integer so we can use it in list-slicing notations:
  max_length max_emails max_email_size poll_interval

When a float is used in the slicing notation you would see
errors similar to:

>>> 'abc'[1.1:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: slice indices must be integers or None or have an __index__ method

Thanks Alan for the bug report!

[git-p4: depot-paths = "//guest/lester_cheung/p4review/": change = 10727]